# Generated by Django 6.0.5 on 2026-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cor',
            field=models.CharField(default='#FFF2E5', max_length=7),
        ),
    ]
